// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPba_JkVgblFalb5qdxpMn0GdenzEjvC0',
    appId: '1:607720209159:web:8e3a3e1644ad062f7be3a2',
    messagingSenderId: '607720209159',
    projectId: 'notification-appmamnon',
    authDomain: 'notification-appmamnon.firebaseapp.com',
    storageBucket: 'notification-appmamnon.appspot.com',
    measurementId: 'G-3EDPJPFEYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjb80vFI9EcTqml-Opvpi1jgeo10Jh_Is',
    appId: '1:607720209159:android:75cefc23127b7aac7be3a2',
    messagingSenderId: '607720209159',
    projectId: 'notification-appmamnon',
    storageBucket: 'notification-appmamnon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg55t49qYFkSYRqeyXnkMDqq8IzEEQZA8',
    appId: '1:607720209159:ios:4d030c3e2242ecfb7be3a2',
    messagingSenderId: '607720209159',
    projectId: 'notification-appmamnon',
    storageBucket: 'notification-appmamnon.appspot.com',
    iosBundleId: 'com.example.appflutterOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg55t49qYFkSYRqeyXnkMDqq8IzEEQZA8',
    appId: '1:607720209159:ios:da8487118feebd7e7be3a2',
    messagingSenderId: '607720209159',
    projectId: 'notification-appmamnon',
    storageBucket: 'notification-appmamnon.appspot.com',
    iosBundleId: 'com.example.appflutterOne.RunnerTests',
  );
}
